const accentHighlight = '#00d9ff';
const accentGradientMid = '#4895ef';
const accentGradientEnd = '#9d4edd';
const pageBackground = '#0a0e27';
const sectionBackground = '#151934';
const cardBackground = '#1a1f3a';
const textDefault = '#e4e6eb';
const textMuted = '#b0b3b8';
const border = '#2a2f4a';
const modalOverlay = 'rgba(0, 0, 0, 0.9)';

export const theme = {
  colors: {
    pageBackground,
    sectionBackground,
    cardBackground,
    textDefault,
    textMuted,
    accentHighlight,
    accentGradientMid,
    accentGradientEnd,
    border,
    modalOverlay,
    navBackground: `${pageBackground}f0`,
  },
  gradients: {
    accent: `linear-gradient(90deg, ${accentHighlight} 0%, ${accentGradientMid} 50%, ${accentGradientEnd} 100%)`,
  },
  shadows: {
    small: '0 4px 6px rgba(0, 0, 0, 0.3)',
    large: '0 10px 40px rgba(0, 0, 0, 0.4)',
    hover: '0 20px 60px rgba(0, 0, 0, 0.5)',
  },
  breakpoints: {
    mobile: '480px',
    tablet: '768px',
    desktop: '1200px',
  },
  text: {
    fontSize: {
      profileName: '3rem',
      sectionTitle: '2.5rem',
      pageHeading: '2rem',
      cardHeading: '1.75rem',
      subheading: '1.5rem',
      cardTitle: '1.35rem',
      leadText: '1.25rem',
      navLink: '1.15rem',
      bodyLarge: '1.125rem',
      bodyMedium: '1rem',
      bodySmall: '0.9rem',
      caption: '0.875rem',
      tag: '0.8rem',
    },
    fontWeight: {
      light: 300,
      medium: 500,
      semiBold: 600,
      bold: 700,
    },
    lineHeight: {
      tight: 1.6,
      normal: 1.7,
      relaxed: 1.8,
    },
  },
  spacing: {
    linkUnderlinePadding: '0.25rem',
    micro: '0.3rem',
    compact: '0.5rem',
    tight: '0.75rem',
    standard: '1rem',
    comfortable: '1.5rem',
    relaxed: '2rem',
    spacious: '3rem',
    section: '4rem',
    navOffset: '5rem',
    twoAndHalf: '2.5rem',
    sectionLarge: '3.5rem',
    navLinkGap: '2.5rem',
    navLinkGapTablet: '1.75rem',
    navLinkGapMobile: '1.25rem',
    negativeListMarkerOffset: '-0.35rem',
  },
  sizes: {
    appMaxWidth: '1240px',
    navMaxWidth: '1400px',
    skillsGridMaxWidth: '1000px',
    bioContentMaxWidth: '800px',
    contactLinksMaxWidth: '350px',
    contactLinksMobileMaxWidth: '300px',
    profileImageDesktop: '300px',
    profileImageTablet: '200px',
    profileImageMobile: '150px',
    navProfileImage: '2.5rem',
    modalImageWidth: '75vw',
    modalImageHeight: '75vh',
    closeButton: '3rem',
    closeButtonMobile: '2.5rem',
    navButton: '3.5rem',
    navButtonMobile: '3rem',
    navLinkUnderlineHeight: '2px',
    navLinkUnderlineOffset: '-2px',
    projectImageMultiMax: '400px',
    projectImageTabletMax: '80vw',
    projectImageMobileMax: '85vw',
    projectImageTabletHeight: '250px',
    projectImageMobileHeight: '200px',
    skillIcon: 50,
    contactIcon: 24,
    screenHeight: '100vh',
  },
  borderRadius: {
    circle: '50%',
    card: '16px',
    contactLink: '12px',
    button: '8px',
    pill: '20px',
  },
  borders: {
    thin: `1px solid ${border}`,
    standard: `2px solid ${border}`,
    thickAccent: `4px solid ${accentHighlight}`,
    standardAccent: `2px solid ${accentHighlight}`,
  },
  zIndex: {
    nav: 100,
    modalBackdrop: 1000,
    modalContent: 1001,
  },
  transitions: {
    hoverAll: 'all 0.3s ease',
    hoverTransform: 'transform 0.3s ease',
    hoverOpacity: 'opacity 0.3s ease',
    hoverColor: 'color 0.3s ease',
    hoverWidth: 'width 0.3s ease',
    navSlide: 'transform 0.3s ease-in-out',
    buttonScale: 'transform 0.2s ease',
  },
  fonts: {
    system:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif",
    fallback: 'Arial, sans-serif',
  },
  animations: {
    duration: '0.3s',
    scaleFrom: '0.8',
    zoomIn: 'zoomIn 0.3s ease',
  },
  grid: {
    cols4: 'repeat(4, 1fr)',
    cols3: 'repeat(3, 1fr)',
    cols2: 'repeat(2, 1fr)',
    autoRows1fr: '1fr',
  },
  transforms: {
    liftSmall: 'translateY(-2px)',
    liftMedium: 'translateY(-5px)',
    centerVertical: 'translateY(-50%)',
    centerVerticalScaleUp: 'translateY(-50%) scale(1.1)',
    hoverScale: 'scale(1.05)',
    scaleIdentity: 'scale(1)',
    rotateClose: 'rotate(90deg)',
    navVisible: 'translateY(0)',
    navHidden: 'translateY(-100%)',
  },
  cssValues: {
    backgroundClip: { text: 'text' },
    color: { transparent: 'transparent', inherit: 'inherit' },
    display: { flex: 'flex', grid: 'grid', inlineBlock: 'inline-block', none: 'none' },
    flexDirection: { column: 'column' },
    flexWrap: { wrap: 'wrap' },
    alignItems: { center: 'center', flexStart: 'flex-start' },
    justifyContent: { center: 'center', spaceBetween: 'space-between', flexStart: 'flex-start' },
    position: { fixed: 'fixed', absolute: 'absolute', relative: 'relative' },
    inset: { zero: '0', full: '100%', half: '50%' },
    textAlign: { center: 'center' },
    textDecoration: { none: 'none' },
    fontStyle: { italic: 'italic' },
    listStyle: { none: 'none' },
    objectFit: { cover: 'cover', contain: 'contain' },
    width: { full: '100%', fitContent: 'fit-content', zero: '0' },
    margin: { auto: 'auto' },
    content: { empty: "''", bullet: "'▹'" },
    cursor: { pointer: 'pointer' },
    userSelect: { none: 'none' },
    touchAction: { none: 'none' },
    overflow: { auto: 'auto', hidden: 'hidden' },
    overflowScrolling: { touch: 'touch' },
    scrollSnap: { xMandatory: 'x mandatory' },
    scrollbarWidth: { none: 'none' },
    fontSmoothing: { antialiased: 'antialiased', grayscale: 'grayscale' },
    boxSizing: { borderBox: 'border-box' },
    backdropFilter: { navBlur: 'blur(12px)' },
    opacity: { zero: '0', full: '1', imageHover: '0.9' },
  },
};

export type Theme = typeof theme;

export const gradientColours = {
  accentHighlight: theme.colors.accentHighlight,
  accentGradientMid: theme.colors.accentGradientMid,
  accentGradientEnd: theme.colors.accentGradientEnd,
} as const;

export const sectionBackgrounds = {
  pageBackground: theme.colors.pageBackground,
  sectionBackground: theme.colors.sectionBackground,
  cardBackground: theme.colors.cardBackground,
} as const;
